id: hookshot
as_token: aaaaaaaaaa
hs_token: aaaaaaaaaa
namespaces:
  users:
    - regex: "@webhook_.*:local"
      exclusive: true

sender_localpart: hookshot
url: "http://hookshot:9993"
rate_limited: false

# If enabling encryption
de.sorunome.msc2409.push_ephemeral: true
# org.matrix.msc3202: true
