# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "local"
pid_file: /run/matrix-synapse.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /volume/homeserver.db
log_config: "/data/local.log.config"
media_store_path: /volume/media_store
registration_shared_secret: "9wUmU4dl=n-kiUy~r*JSktYyR5ue2Dg^T9o:FeX.&&h5V*B0x@"
report_stats: false
macaroon_secret_key: "m5heyvSbNdn3VKddVaKCWb2~GEcq5kSbLGVzfE&hG&fQdQg3U8"
form_secret: "2rGX1Ub9sZO6L:kr8XGiI3cZVOeYD,LC06VsiuxzgWvSjZ=1&s"
signing_key_path: "/data/local.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

app_service_config_files:
  - /data/appservices/enctest.yaml
  - /data/appservices/hookshot.yaml

experimental_features:
  msc3202_device_masquerading: true
  msc3202_transaction_extensions: true
  msc2409_to_device_messages_enabled: true
# vim:ft=yaml
